# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\CZQ\Desktop\czq_dev\All\churuku_query\UI\ui_root.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pymysql
from datetime import datetime
import time
import sys
import xlutils,xlwt
from PyQt5.QtWidgets import (QMenu, QPushButton, QWidget, QTableWidget, QVBoxLayout, QHBoxLayout, QApplication, QTableWidgetItem,
                             QAbstractItemView, QHeaderView, QMainWindow, QInputDialog, QMessageBox, QFileDialog)
from PyQt5.QtCore import QObject, Qt, QDir
from PyQt5.QtGui import *
from sql import *
from PyQt5 import QtCore, QtGui, QtWidgets
from DateDialog import DateDialog
from DoubleDateDialog import DoubleDateDialog
import os
from PyQt5 import QtCore, QtGui, QtWidgets


class TableWidgetContextMenu0(QWidget):
      

                
        def __init__(self):
                super(TableWidgetContextMenu0,self).__init__()
                self.setupUi()
        def setupUi(self):
        
                self.setObjectName("Dialog")
                self.setFixedSize(646, 414)
                self.setStyleSheet("QWidget {\n"
                "border-image:url(new/登录背景.jpg);\n"
                "}\n"
                "\n"
                "#下面的防止背景干扰其他控件\n"
                "QTextBrowser {\n"
                "border-image:url();\n"
                "}\n"
                "QLineEdit {\n"
                "border-image:url();\n"
                "}\n"
                "QComboBox {\n"
                "border-image:url();\n"
                "}\n"
                "QLabel {\n"
                "border-image:url();\n"
                "}\n"
                "QPushButton {\n"
                "border-image:url();\n"
                "}\n"
                "QTableWidget {\n"
                "border-image:url();\n"
                "}\n"
                "\n"
                "")
                
                self.labels=['负责人名称', '电话']
               
                self.tableWidget = QtWidgets.QTableWidget()
                self.tableWidget.setGeometry(QtCore.QRect(10, 30, 621, 311))
                
                self.tableWidget.setObjectName("tableWidget")
                self.tableWidget.setColumnCount(2)
                self.tableWidget.setHorizontalHeaderLabels(self.labels)
                self.tableWidget.horizontalHeader().setStretchLastSection(True)
                self.tableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
                self.pushButton = QtWidgets.QPushButton()
                self.pushButton.setGeometry(QtCore.QRect(90, 360, 151, 28))
                font = QtGui.QFont()
                font.setFamily("微软雅黑")
                font.setPointSize(10)
                self.pushButton.setFont(font)
                self.pushButton.setStyleSheet("QPushButton{\n"
                "background-color:rgba(135,206,235,200);\n"
                "color:#ffffff;\n"
                "}")
                self.pushButton.setObjectName("pushButton")
                self.pushButton_2 = QtWidgets.QPushButton()
                self.pushButton_2.setGeometry(QtCore.QRect(380, 360, 141, 28))
                font = QtGui.QFont()
                font.setFamily("微软雅黑")
                font.setPointSize(10)
                self.pushButton_2.setFont(font)
                self.pushButton_2.setStyleSheet("QPushButton{\n"
                "background-color:rgba(135,206,235,200);\n"
                "color:#ffffff;\n"
                "}")
                self.pushButton_2.setObjectName("pushButton_2")

                self.retranslateUi()
                QtCore.QMetaObject.connectSlotsByName()
        
        def show_table(self):
                data = root_query()
                self.show_query(data)
        def handle_flush(self):
                data = root_query()
                self.show_query(data)    
        def show_query(self,data):
                ##生成表格
                self.tableWidget.clearContents()
                if data:
                        self.tableWidget.setRowCount(len(data))
                for i in range(0,len(data)):
                        item = data[i]
                        for j in range(0,len(item)):
                                newItem = QTableWidgetItem(str(item[j]))
                        self.tableWidget.setItem(i, j, newItem)
                else:
                        self.tableWidget.setRowCount(1)
                        newItem = QTableWidgetItem("未找到")
                        self.tableWidget.setItem(0, 0, newItem)


        ##双击排序     
        ##def HorSectionClicked(self,index):
        
            
        ##双击单元格修改
        def table_double_clicked(self,index):
                if index.column() == 0:
                        QMessageBox.about(self,'警告','用户名不可修改！')
                elif index.column() == 1:
                        text, ok = QInputDialog.getText(self,'信息修改','用户名为'+str(self.tableWidget.item(index.row(),0).text())\
                                +'\n的'+str(self.labels[index.column()])+'('+str(self.tableWidget.item(index.row(),index.column()).text())\
                                +')\n修改为:')
                if ok:
                        
                        root_modify(str(self.tableWidget.item(index.row(),0).text()),str(text))
                        newItem = QTableWidgetItem(str(text))
                        self.tableWidget.setItem(index.row(),index.column(), newItem)
                        QMessageBox.about(self,'成功','修改成功！')
                
            
        def handle1(self):
                ##设置保存目录
                aim = "C:\\报表\\材料信息\\"
                self.mkdir(aim)
                nowTime=time.strftime("%Y%m%d%H%M%S", time.localtime())
                nowDate=time.strftime("%Y%m%d", time.localtime())
                filename = str(nowTime)+'.xls'
                wbk = xlwt.Workbook(encoding = 'utf-8')
                self.sheet = wbk.add_sheet("材料信息"+nowDate, cell_overwrite_ok=True)
                row = 0
                col = 0
                for i in range(self.tableWidget.columnCount()):
                        self.sheet.write(0, i, str(self.labels[i]))
                for i in range(self.tableWidget.columnCount()):
                        for x in range(self.tableWidget.rowCount()):
                                try:
                                        text = str(self.tableWidget.item(row, col).text())
                                        self.sheet.write(row+1, col, text)
                                        row += 1
                                except AttributeError:
                                        row += 1
                row = 0
                col += 1
                path = aim + filename
                wbk.save(path)
                QMessageBox.about(self,'成功',path+'\n导出成功！')

        def mkdir(self,path):
                path=path.strip()
                path=path.rstrip("\\")
                isExists=os.path.exists(path)
                if not isExists:
                        os.makedirs(path) 
                        return True
                else:
                        return False

        ##上一页调用本页
        def handle_click(self):
                data = root_query()
                self.show_query(data)
        def retranslateUi(self, Dialog):
                _translate = QtCore.QCoreApplication.translate
                Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
                self.pushButton.setText(_translate("Dialog", "刷新"))
                self.pushButton_2.setText(_translate("Dialog", "确认"))
